### ISSUE TITLE
handle kill correctly

### ISSUE THREAD

**Issue by tych0** [lxc/lxcri#21]
Currently, kill.go just resolves the container's init pid and sends it the "kill signal" from the container's spec. This is wrong for several reasons.

1. liblxc sticks an lxc-init in front of every task; it does this because it assumes that this lxc-init is going to be pid 1 in every application container, but that is not true in the pod case. The pod's lxc-init really is pid 1, but other containers (with their lxc-inits) spawned in this pod will *not* be pid 1.

2. We assume that killing the init will kill everything in the container, presumably because this is true for pid 1 in a pidns. But since in the k8s view of containers, the pod owns pid 1, and the containers don't. So our current implementation kills the contianer's lxc-init which is not pid 1, which simply results in the service in the container being reparented to the pod's lxc-init, which does not actually stop the service.

3. We send the signal to lxc-init, instead of the real pid 1. The OCI spec allows the container image to say what signal it would like to receive in order to be killed. Presumably then, the application code understands when it sees a particular signal, it needs to shut down. So we should send that signal to the application code instead of lxc-init, which just swallows it.

It seems like the easiest way to solve this is to configure crio-lxc to just not use lxc-init. Since the applications already understand that they don't really have an init, we don't need to babysit them. It doesn't look like it's currently possible to avoid using lxc-init, though.

**Comment by r10r** [comment]
Hi @tych0  this should be implemented now. 

I look forward for you to review current kill implementation.  
Hope you'lll find the time to do so ;)

> 1. The pod's lxc-init really is pid 1

Yes, but it should not be. The container process should have PID 1, so the lxc-init (`lxcri-init`) must exec the container process. The pods `pause` process complains about that and some sonobuoy conformance tests will fail because of that.

> 2. ... But since in the k8s view of containers, the pod owns pid 1, and the containers don't. 

This is true if PID namespaces are actually shared,
See https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/

The OCI spec itself even permits sharing the PID namespace with the runtime - as far as I know ?

 I finally came up with a solution that works fine regardless if PID namespaces are enabled or not.

* `create` ensures that a container starts in it's own empty cgroup.
* `kill` freezes the container cgroup and signals every container process except the liblxc monitor process.
* `delete` calls kill with `SIGKILL` if the `--force` flag is set 
  and waits for the container monitor process (`lxcri-start`) to die.

https://github.com/lxc/lxcri/blob/cbc79e17a3ee7bfe321b439ed22e627803488772/cgroup.go#L279

https://github.com/lxc/lxcri/blob/cbc79e17a3ee7bfe321b439ed22e627803488772/runtime.go#L365

**Comment by r10r** [comment]
I'll close this right now. Please feel free to re-open if you want to comment or review.
